import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

type Language = 'en' | 'kh';

type Dict = { [key: string]: string | Dict };

const en: Dict = {
  navigation: {
    home: 'Home',
    discover: 'Discover',
    rankings: 'Rankings',
    clips: 'Clips',
    messages: 'Messages',
    partners: 'Guides & Rides',
    profile: 'Profile',
    merchant: 'Business Center',
    admin: 'Admin',
    trips: 'Trips',
    collections: 'Collections',
  },
  common: {
    all: 'All',
    allPlaces: 'All places',
    loading: 'Gathering beautiful places...',
    retry: 'Try again',
    seeMore: 'See more',
    seeLess: 'See less',
    sponsored: 'Sponsored',
    close: 'Close',
  },
  search: {
    placeholder: 'Search places, events, cafes, karaoke and rides in Cambodia...',
  },
  feed: {
    title: 'Cambodia, shared by everyone',
    subtitle: 'Free for Cambodians and visitors worldwide — share and explore every province together.',
    exploreBook: 'Explore & Book',
    boost: 'Boost this gem',
    featured: 'Featured Gem',
    empty: 'No stories here yet',
    emptyHelp: 'Be the first to share a place worth finding.',
    emptySearch: 'No stories match your search',
    emptySearchHelp: 'Try another place name, province, or hashtag.',
  },
  social: {
    forYou: 'For you',
    communityFeed: 'Free community travel feed',
    watchClips: 'Watch short clips',
    hiddenGemTitle: 'Hidden Gem of the Week',
    composerPrompt: 'Share freely: a place, event, or joyful moment...',
    storyPrompt: 'Tell people what makes this place worth finding...',
    placeName: 'Place, venue, or event name',
    chooseProvince: 'Choose province or city',
    chooseDistrict: 'District / Khan (auto from commune)',
    chooseCommune: 'Commune / Sangkat',
    addMedia: 'Add up to 10 photos or one 30s video',
    publish: 'Post free',
    exploreByMood: 'Explore by mood',
    resultsFor: 'Showing stories for',
    follow: 'Follow',
    following: 'Following',
    like: 'Like',
    comment: 'Comment',
    share: 'Share',
    comments: 'comments',
    save: 'Save place',
    firstComment: 'Be the first to share a thought',
    commentPlaceholder: 'Write a comment...',
    everyProvince: 'Joy and hidden gems from every province',
  },
  clips: {
    title: 'SokSan Clips',
    subtitle: '30 seconds of Cambodia',
    empty: 'The first clip is waiting to be shared',
    emptyHelp: 'Post a short travel video from the community feed.',
    views: 'views',
    mute: 'Mute',
    unmute: 'Unmute',
    endMessage: 'You are all caught up — check back soon for more of Cambodia.',
    retryVideo: 'This clip could not load. Tap to retry.',
    dataSaverNote: 'Data saver is on — tap to play videos',
  },
  partners: {
    title: 'Trusted local guides and rides',
    subtitle:
      'Browsing is free for every traveler. Verified tourism businesses pay only for listing and visibility tools.',
    join: 'Register your business',
    registerTitle: 'Grow your local business with SokSan',
  },
  access: {
    eyebrow: 'Open to everyone',
    title: 'Cambodians and international visitors belong here',
    description: 'Posting, liking, commenting, sharing, following, Clips, feed and discovery are always free.',
    social: 'All social features free',
    noPaywall: 'No traveler paywall',
    freeChip: 'Free',
    postingFree: 'Free community posting — no payment or subscription.',
  },
  discovery: {
    title: 'Find your quiet place',
    subtitle: 'Thoughtfully selected by people who call Cambodia home.',
    nearby: 'places nearby',
    budget: 'Est. budget',
    empty: 'No places found',
    emptyHelp: 'Try another category or search term.',
  },
  map: {
    discoverLabel: 'Map of curated places in Cambodia',
    pickTitle: 'Pin your spot on the map',
    pickHelp: 'Tap anywhere on the map to drop your pin.',
    pickMapLabel: 'Location picker map',
    tapToDrop: 'Tap the map to drop a pin',
    confirmPin: 'Use this location',
    close: 'Close map',
    outsideCambodia: 'Outside Cambodia — pick a spot inside the country',
    composerPin: 'Pin on map',
    pinnedAt: 'Pinned at',
    clearPin: 'Remove pin',
  },
  business: {
    ownerEyebrow: 'Business tools',
    dashboardTitle: 'Owner dashboard',
    loginToManage: 'Log in to manage your business on SokSan.',
    noBusinessTitle: 'No business yet',
    noBusinessBody:
      'Register your café, guesthouse, guide service or shop — the Verified tier is free.',
    registerTitle: 'Register your business',
    registerSubtitle:
      'Free Verified tier today. Boosted (paid) adds a spotlight on your profile — never in organic rankings.',
    registerAction: 'Register business',
    registerAnother: 'Register another business',
    nameLabel: 'Business name',
    namePlaceholder: 'e.g. Riverside Café',
    categoryLabel: 'Category',
    phoneLabel: 'Phone',
    descriptionLabel: 'Short description',
    descriptionPlaceholder: 'What makes your place worth a stop?',
    freeVerifiedNote: 'The Verified tier is free. You can upgrade to Boosted any time.',
    tierVerified: 'Verified',
    tierBoosted: 'Boosted',
    status: {
      pending: 'Awaiting review',
      approved: 'Approved',
      rejected: 'Rejected',
    },
    placeLabel: 'Location',
    subscriptionLabel: 'Subscription',
    noSubscription: 'Free Verified tier',
    boostedUntil: 'Boosted until',
    leadsComingSoon: 'Call / message / directions tracking arrives in Phase 4.',
    upgradeAction: 'Upgrade to Boosted',
    upgradeTitle: 'Boost with Bakong KHQR',
    close: 'Close payment dialog',
    creatingInvoice: 'Creating your KHQR invoice…',
    perMonth: 'month',
    scanWithBakong: 'Scan with the Bakong app (or any KHQR app)',
    invoiceExpires: 'expires',
    iHavePaid: 'I have paid — confirm',
    confirmingPayment: 'Confirming payment…',
  },
  leads: {
    call: 'Call',
    message: 'Message',
    directions: 'Directions',
    messageSent: 'Thanks — the business will see your message request.',
    backToDiscover: 'Back to Discover',
    boostedHint: 'Paid spotlight on this profile only — never affects organic ranking.',
    title: 'Leads — last 7 days',
    calls: 'Calls',
    messages: 'Messages',
    directionsLabel: 'Directions',
    total: 'Total',
    viewPublicPage: 'View public page',
    partnerLabel: 'ដៃគូ · Partner',
  },
  admin: {
    eyebrow: 'Moderation & scheduling',
    title: 'Admin panel',
    forbidden: 'Your account does not have the admin role.',
    pendingPosts: 'Pending posts',
    pendingBusinesses: 'Pending businesses',
    placements: 'Partner placements',
    hiddenGem: 'Hidden Gem',
    auditLog: 'Audit log',
    queueEmpty: 'Queue is clear — nothing waiting for review.',
    approve: 'Approve',
    reject: 'Reject',
    approvedNotice: 'Approved — it is now live.',
    rejectedNotice: 'Rejected — the owner can see the decision.',
    placementsHint:
      'Placements are visible only inside their date window and are always labeled ដៃគូ / Partner. They never affect organic ranking.',
    placementUpdated: 'Placement updated.',
    activate: 'Activate',
    deactivate: 'Deactivate',
    openEnded: 'open-ended',
    gemHint: 'Pick ONE published post as this week’s Hidden Gem. Editorial only — ranking scores are untouched.',
    gemPostId: 'Post ID',
    gemNote: 'Editor note (optional)',
    pickGem: 'Set Hidden Gem of the Week',
    gemPicked: 'Hidden Gem of the Week updated.',
    auditEmpty: 'No admin actions recorded yet.',
    duplicates: 'Duplicate places',
    duplicatesHint:
      'Candidate duplicates detected from community posts. Nothing merges until you confirm which place survives.',
    duplicatesEmpty: 'No duplicate candidates detected.',
    duplicateReason: {
      sameName: 'same name in one commune',
      nearby: 'very close together',
    },
    keepA: 'Keep',
    mergedNotice: 'Merged — the duplicate is hidden and the action is in the audit log.',
  },
  trending: {
    title: 'Trending now',
    subtitle: 'Hot in the last few days',
  },
  trips: {
    title: 'Trip planner',
    eyebrow: 'Your collections',
    subtitle: 'Collect places into shareable trip lists — one link shares the whole plan.',
    empty: 'No trips yet. Tap “Trip” on any feed post to start collecting.',
    signInPrompt: 'Sign in to collect places into shareable trip lists.',
    stops: 'stops',
    share: 'Share',
    copied: 'Copied!',
    shareLabel: 'share link',
    privateTag: 'private',
    pickerTitle: 'Add to a trip',
    addHere: 'Add here',
    addShort: 'Trip',
    addLabel: 'Add this place to a trip',
    noneYet: 'No trips yet — create your first one below.',
    newPlaceholder: 'New trip name (e.g. Kampot weekend)',
    createAndAdd: 'Create & add',
    addedNotice: 'Added to your trip.',
    addFailed: 'Could not add that place.',
    createFailed: 'Could not create the trip.',
    by: 'by',
    sharedEyebrow: 'Shared trip',
    notFound: 'This trip is private or does not exist.',
    noStops: 'No stops in this trip yet.',
  },
  offline: {
    title: 'Offline library',
    eyebrow: 'Saved on your device',
    subtitle: 'Posts you saved keep working with no signal — remove them any time.',
    empty: 'Nothing saved yet. Tap “Offline” on a post to keep it for later.',
    savedAt: 'saved',
    remove: 'Remove from offline library',
    saveShort: 'Offline',
    banner: 'You are offline — saved places still work.',
    openLibrary: 'Open library',
  },
  contributor: {
    title: 'Your contributor level',
    points: 'quality points',
    toNext: 'to',
    formulaLabel: 'How points are calculated',
    badge: {
      first_story: 'First story',
      prolific: '10+ stories',
      beloved: '100+ likes received',
      word_spreader: '50+ shares',
    },
  },
  collections: {
    title: 'Community collections',
    eyebrow: 'Public curation',
    subtitle: 'Curated places shared by travelers — browse them all, or start your own.',
    empty: 'No collections yet. Create the first one!',
    create: 'Create',
    newPlaceholder: 'Collection name (e.g. Best coffee in Phnom Penh)',
    places: 'places',
    by: 'by',
    pickerTitle: 'Add to a collection',
    addHere: 'Add here',
    addShort: 'Collect',
    addLabel: 'Add this place to a public collection',
    noneYet: 'No collections yet — create your first one below.',
    createAndAdd: 'Create & add',
    addedNotice: 'Added to your collection.',
    addFailed: 'Could not add that place.',
    createFailed: 'Could not create the collection.',
    sharedEyebrow: 'Public collection',
    notFound: 'This collection does not exist.',
    noPlaces: 'No places in this collection yet.',
  },
  chat: {
    title: 'Travel Chat',
    localGuides: 'Local Guides',
    activeNow: 'Active now',
    typeMessage: 'Write a message...',
    sharePlace: 'Share Place',
    pinLocation: 'Pin Location',
    shareItinerary: 'Itinerary',
    choosePlace: 'Pin a place to this chat',
  },
  profile: {
    expertise: 'Local expertise',
    services: 'Experiences & stays',
    servicesSubtitle: 'Travel slowly. Meet the people who know these landscapes best.',
    book: 'Book experience',
  },
  payment: {
    secure: 'Secure KHQR payment',
    guestName: 'Your name',
    scanPay: 'Scan to pay with any Bakong member bank',
    confirm: 'Confirm instant payment',
    received: 'Instant Payment Received',
  },
  ranking: {
    title: 'Cambodia Provinces Top List',
    subtitle: 'A living pulse of the places travelers love, shaped by real check-ins and local reviews.',
  },
  auth: {
    loginTitle: 'Welcome back',
    loginSubtitle: 'Log in to post places, save gems and follow local storytellers.',
    registerTitle: 'Join SokSan free',
    registerSubtitle: 'Create a free account to share Cambodia’s hidden gems.',
    name: 'Your name',
    namePlaceholder: 'e.g. Dara Sok',
    email: 'Email',
    password: 'Password',
    confirm: 'Confirm password',
    loginAction: 'Log in',
    registerAction: 'Create account',
    noAccount: 'New to SokSan?',
    haveAccount: 'Already have an account?',
    logout: 'Log out',
    loginNav: 'Log in',
    joinNav: 'Join free',
    nameError: 'Please enter your name (at least 2 characters).',
    emailError: 'Please enter a valid email address.',
    passwordError: 'Password must be at least 8 characters.',
    confirmError: 'Passwords do not match.',
    genericError: 'Something went wrong. Please try again.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    composerLoginTitle: 'Log in to share your places',
    composerLoginBody: 'Posting, liking, commenting and saving are free — you just need an account.',
    composerLoginCta: 'Log in or join free',
    savedOnly: 'Log in to save places to your list.',
  },
};

const kh: Dict = {
  navigation: {
    home: 'ទំព័រដើម',
    discover: 'រុករក',
    rankings: 'ចំណាត់ថ្នាក់',
    clips: 'វីដេអូខ្លី',
    messages: 'សារ',
    partners: 'មគ្គុទ្ទេសក៍ និងយានជំនិះ',
    profile: 'ប្រវត្តិរូប',
    merchant: 'មជ្ឈមណ្ឌលអាជីវកម្ម',
    admin: 'អ្នកគ្រប់គ្រង',
    trips: 'ដំណើរ',
    collections: 'ការប្រមូល',
  },
  common: {
    all: 'ទាំងអស់',
    allPlaces: 'គ្រប់ទីកន្លែង',
    loading: 'កំពុងប្រមូលទីកន្លែងស្អាតៗ...',
    retry: 'ព្យាយាមម្ដងទៀត',
    seeMore: 'មើលបន្ថែម',
    seeLess: 'បង្ហាញតិច',
    sponsored: 'ដៃគូឧបត្ថម្ភ',
    close: 'បិទ',
  },
  search: {
    placeholder: 'ស្វែងរកទីកន្លែង ព្រឹត្តិការណ៍ កាហ្វេ ខារ៉ាអូខេ និងយានជំនិះនៅកម្ពុជា...',
  },
  feed: {
    title: 'កម្ពុជា ចែករំលែកដោយគ្រប់គ្នា',
    subtitle: 'ឥតគិតថ្លៃសម្រាប់ប្រជាជនកម្ពុជា និងភ្ញៀវអន្តរជាតិ — ចែករំលែក និងរុករកគ្រប់ខេត្តជាមួយគ្នា។',
    exploreBook: 'រុករក និងកក់',
    boost: 'ជំរុញកន្លែងនេះ',
    featured: 'ត្បូងពិសេស',
    empty: 'មិនទាន់មានរឿងរ៉ាវនៅទីនេះ',
    emptyHelp: 'ក្លាយជាអ្នកដំបូងដែលចែករំលែកកន្លែងគួរឱ្យទៅ។',
    emptySearch: 'គ្មានរឿងរ៉ាវត្រូវនឹងការស្វែងរករបស់អ្នក',
    emptySearchHelp: 'សាកល្បងឈ្មោះកន្លែង ខេត្ត ឬហែសថែកផ្សេង។',
  },
  social: {
    forYou: 'សម្រាប់អ្នក',
    communityFeed: 'ព័ត៌មានដំណើរសហគមន៍ឥតគិតថ្លៃ',
    watchClips: 'មើលវីដេអូខ្លី',
    hiddenGemTitle: 'ត្បូងលាក់ប្រចាំសប្តាហ៍',
    composerPrompt: 'ចែករំលែកដោយឥតគិតថ្លៃ៖ ទីកន្លែង ព្រឹត្តិការណ៍ ឬពេលវេលារីករាយ...',
    storyPrompt: 'ប្រាប់អ្នកដទៃថាហេតុអ្វីទីកន្លែងនេះគួរឱ្យចង់ទៅ...',
    placeName: 'ឈ្មោះទីកន្លែង ឬព្រឹត្តិការណ៍',
    chooseProvince: 'ជ្រើសរើសខេត្ត ឬក្រុង',
    chooseDistrict: 'ស្រុក / ខណ្ឌ (ស្វ័យប្រវត្តិពីឃុំ)',
    chooseCommune: 'ឃុំ / សង្កាត់',
    addMedia: 'បន្ថែមរូបភាពរហូតដល់ ១០ ឬវីដេអូ ៣០វិនាទីមួយ',
    publish: 'បង្ហោះឥតគិតថ្លៃ',
    exploreByMood: 'រុករកតាមអារម្មណ៍',
    resultsFor: 'បង្ហាញរឿងរ៉ាវសម្រាប់',
    follow: 'តាមដាន',
    following: 'កំពុងតាមដាន',
    like: 'ចូលចិត្ត',
    comment: 'មតិ',
    share: 'ចែករំលែក',
    comments: 'មតិ',
    save: 'រក្សាទុកកន្លែង',
    firstComment: 'ក្លាយជាអ្នកដំបូងដែលចែករំលែកមតិ',
    commentPlaceholder: 'សរសេរមតិ...',
    everyProvince: 'ភាពរីករាយ និងកន្លែងលាក់ខ្លួនពីគ្រប់ខេត្ត',
  },
  clips: {
    title: 'វីដេអូខ្លីសុខសាន្ត',
    subtitle: '៣០វិនាទីនៃកម្ពុជា',
    empty: 'វីដេអូដំបូងកំពុងរង់ចាំការចែករំលែក',
    emptyHelp: 'បង្ហោះវីដេអូដំណើរខ្លីពីទំព័រព័ត៌មានសហគមន៍។',
    views: 'អ្នកមើល',
    mute: 'បិទសម្លេង',
    unmute: 'បើកសម្លេង',
    endMessage: 'អ្នកបានមើលអស់ហើយ — ត្រឡប់មកវិញពេលក្រោយ សម្រាប់កម្ពុជាបន្ថែម។',
    retryVideo: 'វីដេអូនេះផ្ទុកមិនបាន។ ចុចដើម្បីព្យាយាមម្ដងទៀត។',
    dataSaverNote: 'របៀបសន្សំទិន្នន័យបើក — ចុចដើម្បីមើលវីដេអូ',
  },
  partners: {
    title: 'មគ្គុទ្ទេសក៍ និងយានជំនិះក្នុងស្រុកដែលទុកចិត្តបាន',
    subtitle:
      'ការរុករកឥតគិតថ្លៃសម្រាប់អ្នកដំណើរគ្រប់គ្នា។ អាជីវកម្មទេសចរណ៍បង់តែសម្រាប់ការចុះបញ្ជី និងការបង្ហាញពិសេស។',
    join: 'ចុះឈ្មោះអាជីវកម្មរបស់អ្នក',
    registerTitle: 'ពង្រីកអាជីវកម្មក្នុងស្រុកជាមួយសុខសាន្ត',
  },
  access: {
    eyebrow: 'បើកចំហសម្រាប់គ្រប់គ្នា',
    title: 'ប្រជាជនកម្ពុជា និងភ្ញៀវអន្តរជាតិទាំងអស់ស្វាគមន៍',
    description: 'ការបង្ហោះ ចូលចិត្ត មតិ ចែករំលែក តាមដាន វីដេអូខ្លី ព័ត៌មាន និងផែនទី គឺឥតគិតថ្លៃជានិច្ច។',
    social: 'មុខងារសង្គមទាំងអស់ឥតគិតថ្លៃ',
    noPaywall: 'គ្មានការបង់ប្រាក់សម្រាប់អ្នកដំណើរ',
    freeChip: 'ឥតគិតថ្លៃ',
    postingFree: 'ការបង្ហោះសហគមន៍ឥតគិតថ្លៃ — គ្មានការទូទាត់ ឬសមាជិកភាព។',
  },
  discovery: {
    title: 'ស្វែងរកទីស្ងប់ស្ងាត់របស់អ្នក',
    subtitle: 'ជ្រើសរើសយ៉ាងយកចិត្តទុកដាក់ដោយអ្នកដែលហៅកម្ពុជាថាផ្ទះ។',
    nearby: 'កន្លែងនៅជិត',
    budget: 'ថវិកាប៉ាន់ស្មាន',
    empty: 'រកមិនឃើញកន្លែង',
    emptyHelp: 'សាកល្បងប្រភេទ ឬពាក្យស្វែងរកផ្សេង។',
  },
  map: {
    discoverLabel: 'ផែនទីនៃកន្លែងដែលបានជ្រើសរើសនៅកម្ពុជា',
    pickTitle: 'ដាក់ខ្ទាស់ទីតាំងរបស់អ្នកលើផែនទី',
    pickHelp: 'ចុចគ្រប់ទីកន្លែងលើផែនទី ដើម្បីដាក់ខ្ទាស់របស់អ្នក។',
    pickMapLabel: 'ផែនទីសម្រាប់ជ្រើសរើសទីតាំង',
    tapToDrop: 'ចុចផែនទី ដើម្បីដាក់ខ្ទាស់',
    confirmPin: 'ប្រើទីតាំងនេះ',
    close: 'បិទផែនទី',
    outsideCambodia: 'នៅក្រៅកម្ពុជា — សូមជ្រើសរើសទីតាំងក្នុងប្រទេស',
    composerPin: 'ដាក់ខ្ទាស់លើផែនទី',
    pinnedAt: 'បានដាក់ខ្ទាស់នៅ',
    clearPin: 'ដកខ្ទាស់ចេញ',
  },
  business: {
    ownerEyebrow: 'ឧបករណ៍អាជីវកម្ម',
    dashboardTitle: 'ផ្ទាំងគ្រប់គ្រងម្ចាស់អាជីវកម្ម',
    loginToManage: 'ចូលគណនី ដើម្បីគ្រប់គ្រងអាជីវកម្មរបស់អ្នកនៅលើ សុខសាន្ត។',
    noBusinessTitle: 'មិនទាន់មានអាជីវកម្ម',
    noBusinessBody:
      'ចុះឈ្មោះហាងកាហ្វេ ផ្ទះសំណាក់ សេវាកម្មមគ្គុទ្ទេសក៍ ឬហាងរបស់អ្នក — កម្រិតផ្ទៀងផ្ទាត់ឥតគិតថ្លៃ។',
    registerTitle: 'ចុះឈ្មោះអាជីវកម្មរបស់អ្នក',
    registerSubtitle:
      'កម្រិតផ្ទៀងផ្ទាត់ឥតគិតថ្លៃថ្ងៃនេះ។ កម្រិតបុស្ទ (គិតថ្លៃ) បន្ថែមការបង្ហាញលើទំព័ររបស់អ្នក — មិនប៉ះពាល់ចំណាត់ថ្នាក់ធម្មជាតិទេ។',
    registerAction: 'ចុះឈ្មោះអាជីវកម្ម',
    registerAnother: 'ចុះឈ្មោះអាជីវកម្មមួយទៀត',
    nameLabel: 'ឈ្មោះអាជីវកម្ម',
    namePlaceholder: 'ឧ. កាហ្វេមាត់ទន្លេ',
    categoryLabel: 'ប្រភេទ',
    phoneLabel: 'លេខទូរស័ព្ទ',
    descriptionLabel: 'ការពិពណ៌នាខ្លី',
    descriptionPlaceholder: 'តើកន្លែងរបស់អ្នកពិសេសត្រង់ណា?',
    freeVerifiedNote: 'កម្រិតផ្ទៀងផ្ទាត់ឥតគិតថ្លៃ។ អ្នកអាចដំឡើងទៅកម្រិតបុស្ទគ្រប់ពេល។',
    tierVerified: 'បានផ្ទៀងផ្ទាត់',
    tierBoosted: 'បុស្ទ',
    status: {
      pending: 'កំពុងរង់ចាំការពិនិត្យ',
      approved: 'បានអនុម័ត',
      rejected: 'បានបដិសេធ',
    },
    placeLabel: 'ទីតាំង',
    subscriptionLabel: 'ការជាវ',
    noSubscription: 'កម្រិតផ្ទៀងផ្ទាត់ឥតគិតថ្លៃ',
    boostedUntil: 'បុស្ទរហូតដល់',
    leadsComingSoon: 'ការតាមដានការហៅ/សារ/ផ្លូវ នឹងមកដល់ក្នុងដំណាក់កាលទី ៤។',
    upgradeAction: 'ដំឡើងទៅកម្រិតបុស្ទ',
    upgradeTitle: 'បុស្ទជាមួយ បាគង KHQR',
    close: 'បិទផ្ទាំងការទូទាត់',
    creatingInvoice: 'កំពុងបង្កើតវិក្កយបត្រ KHQR…',
    perMonth: 'ខែ',
    scanWithBakong: 'ស្កេនដោយកម្មវិធី បាគង (ឬកម្មវិធី KHQR ណាមួយ)',
    invoiceExpires: 'ផុតកំណត់',
    iHavePaid: 'ខ្ញុំបានបង់រួច — បញ្ជាក់',
    confirmingPayment: 'កំពុងបញ្ជាក់ការទូទាត់…',
  },
  leads: {
    call: 'ហៅទូរស័ព្ទ',
    message: 'ផ្ញើសារ',
    directions: 'បង្ហាញផ្លូវ',
    messageSent: 'អរគុណ — អាជីវកម្មនឹងឃើញសំណើសាររបស់អ្នក។',
    backToDiscover: 'ត្រឡប់ទៅរុករក',
    boostedHint: 'ការបង្ហាញបង់ថ្លៃលើទំព័រនេះប៉ុណ្ណោះ — មិនប៉ះពាល់ចំណាត់ថ្នាក់ធម្មជាតិទេ។',
    title: 'ការចាប់អារម្មណ៍ — ៧ ថ្ងៃចុងក្រោយ',
    calls: 'ការហៅ',
    messages: 'សារ',
    directionsLabel: 'បង្ហាញផ្លូវ',
    total: 'សរុប',
    viewPublicPage: 'មើលទំព័រសាធារណៈ',
    partnerLabel: 'ដៃគូ · Partner',
  },
  admin: {
    eyebrow: 'សម្របសម្រួល និងកាលវិភាគ',
    title: 'ផ្ទាំងអ្នកគ្រប់គ្រង',
    forbidden: 'គណនីរបស់អ្នកមិនមានតួនាទីអ្នកគ្រប់គ្រងទេ។',
    pendingPosts: 'ប្រកាសរង់ចាំ',
    pendingBusinesses: 'អាជីវកម្មរង់ចាំ',
    placements: 'ការបង្ហាញដៃគូ',
    hiddenGem: 'ត្បូងលាក់',
    auditLog: 'កំណត់ហេតុសវនកម្ម',
    queueEmpty: 'ជួរទទេ — គ្មានអ្វីរង់ចាំការពិនិត្យ។',
    approve: 'អនុម័ត',
    reject: 'បដិសេធ',
    approvedNotice: 'បានអនុម័ត — ឥឡូវនេះបង្ហាញជាសាធារណៈ។',
    rejectedNotice: 'បានបដិសេធ — ម្ចាស់អាចមើលការសម្រេចចិត្ត។',
    placementsHint:
      'ការបង្ហាញដៃគូបង្ហាញតែក្នុងចន្លោះកាលបរិច្ឆេទ ហើយត្រូវបានដាក់ស្លាក ដៃគូ / Partner ជានិច្ច។ វាមិនប៉ះពាល់ចំណាត់ថ្នាក់ធម្មជាតិទេ។',
    placementUpdated: 'បានធ្វើបច្ចុប្បន្នភាពការបង្ហាញ។',
    activate: 'បើក',
    deactivate: 'បិទ',
    openEnded: 'គ្មានកាលបរិច្ឆេទបញ្ចប់',
    gemHint: 'ជ្រើសរើសប្រកាសមួយដែលបានផ្សាយជា ត្បូងលាក់ សប្តាហ៍នេះ។ ជាការជ្រើសរើសរបស់អ្នកគ្រប់គ្រង — ពិន្ទុចំណាត់ថ្នាក់មិនផ្លាស់ប្តូរ។',
    gemPostId: 'លេខសម្គាល់ប្រកាស',
    gemNote: 'កំណត់ចំណាំ (ស្រេចចិត្ត)',
    pickGem: 'កំណត់ត្បូងលាក់សប្តាហ៍នេះ',
    gemPicked: 'បានធ្វើបច្ចុប្បន្នភាពត្បូងលាក់សប្តាហ៍នេះ។',
    auditEmpty: 'មិនទាន់មានសកម្មភាពអ្នកគ្រប់គ្រងបានកត់ត្រា។',
    duplicates: 'ទីកន្លែងស្ទួន',
    duplicatesHint:
      'ការរកឃើញទីកន្លែងស្ទួនពីប្រកាសសហគមន៍។ មិនមានការបញ្ចូលគ្នាទេ រហូតដល់អ្នកបញ្ជាក់ថាទីកន្លែងណាត្រូវរក្សាទុក។',
    duplicatesEmpty: 'មិនបានរកឃើញទីកន្លែងស្ទួនទេ។',
    duplicateReason: {
      sameName: 'ឈ្មោះដូចគ្នាក្នុងឃុំតែមួយ',
      nearby: 'នៅជិតគ្នាខ្លាំង',
    },
    keepA: 'រក្សាទុក',
    mergedNotice: 'បានបញ្ចូលគ្នា — ទីកន្លែងស្ទួនត្រូវបានលាក់ ហើយសកម្មភាពស្ថិតក្នុងកំណត់ហេតុសវនកម្ម។',
  },
  trending: {
    title: 'កំពុងពេញនិយម',
    subtitle: 'ក្តៅក្នុងប៉ុន្មានថ្ងៃចុងក្រោយ',
  },
  trips: {
    title: 'កម្មវិធីរៀបចំដំណើរ',
    eyebrow: 'ការប្រមូលរបស់អ្នក',
    subtitle: 'ប្រមូលទីកន្លែងទៅក្នុងបញ្ជីដំណើរដែលអាចចែករំលែកបាន — តំណតែមួយចែករំលែកផែនការទាំងមូល។',
    empty: 'មិនទាន់មានដំណើរទេ។ ចុច “ដំណើរ” លើប្រកាសណាមួយដើម្បីចាប់ផ្តើមប្រមូល។',
    signInPrompt: 'ចូលគណនី ដើម្បីប្រមូលទីកន្លែងទៅក្នុងបញ្ជីដំណើរដែលអាចចែករំលែកបាន។',
    stops: 'ទីកន្លែង',
    share: 'ចែករំលែក',
    copied: 'បានចម្លង!',
    shareLabel: 'តំណចែករំលែក',
    privateTag: 'ឯកជន',
    pickerTitle: 'បន្ថែមទៅដំណើរ',
    addHere: 'បន្ថែមទីនេះ',
    addShort: 'ដំណើរ',
    addLabel: 'បន្ថែមទីកន្លែងនេះទៅដំណើរ',
    noneYet: 'មិនទាន់មានដំណើរ — បង្កើតដំណើរដំបូងខាងក្រោម។',
    newPlaceholder: 'ឈ្មោះដំណើរថ្មី (ឧ. ចុងសប្តាហ៍កំពត)',
    createAndAdd: 'បង្កើត និងបន្ថែម',
    addedNotice: 'បានបន្ថែមទៅដំណើររបស់អ្នក។',
    addFailed: 'មិនអាចបន្ថែមទីកន្លែងនោះបានទេ។',
    createFailed: 'មិនអាចបង្កើតដំណើរបានទេ។',
    by: 'ដោយ',
    sharedEyebrow: 'ដំណើរដែលបានចែករំលែក',
    notFound: 'ដំណើរនេះជាឯកជន ឬមិនមានទេ។',
    noStops: 'មិនទាន់មានទីកន្លែងក្នុងដំណើរនេះ។',
  },
  offline: {
    title: 'បណ្ណាល័យអ៊ូបឡាញ',
    eyebrow: 'បានរក្សាទុកក្នុងឧបករណ៍របស់អ្នក',
    subtitle: 'ប្រកាសដែលអ្នកបានរក្សាទុក នៅប្រើបានទោះគ្មានសេវា — លុបចេញបានគ្រប់ពេល។',
    empty: 'មិនទាន់បានរក្សាទុកអ្វីទេ។ ចុច “អ៊ូបឡាញ” លើប្រកាស ដើម្បីទុកសម្រាប់ពេលក្រោយ។',
    savedAt: 'បានរក្សាទុក',
    remove: 'លុបចេញពីបណ្ណាល័យអ៊ូបឡាញ',
    saveShort: 'អ៊ូបឡាញ',
    banner: 'អ្នកកំពុងអ៊ូបឡាញ — ទីកន្លែងដែលបានរក្សាទុក នៅប្រើបាន។',
    openLibrary: 'បើកបណ្ណាល័យ',
  },
  contributor: {
    title: 'កម្រិតអ្នកចូលរួមរបស់អ្នក',
    points: 'ពិន្ទុគុណភាព',
    toNext: 'ទៅ',
    formulaLabel: 'របៀបគណនាពិន្ទុ',
    badge: {
      first_story: 'រឿងដំបូង',
      prolific: 'រឿង 10+',
      beloved: 'ចូលចិត្ត 100+',
      word_spreader: 'ចែករំលែក 50+',
    },
  },
  collections: {
    title: 'ការប្រមូលសហគមន៍',
    eyebrow: 'ការរៀបចំសាធារណៈ',
    subtitle: 'ទីកន្លែងដែលអ្នកដំណើររៀបចំ និងចែករំលែក — រុករកទាំងអស់ ឬបង្កើតរបស់អ្នកផ្ទាល់។',
    empty: 'មិនទាន់មានការប្រមូលទេ។ បង្កើតមួយដំបូង!',
    create: 'បង្កើត',
    newPlaceholder: 'ឈ្មោះការប្រមូល (ឧ. កាហ្វេល្អបំផុតក្នុងភ្នំពេញ)',
    places: 'ទីកន្លែង',
    by: 'ដោយ',
    pickerTitle: 'បន្ថែមទៅការប្រមូល',
    addHere: 'បន្ថែមទីនេះ',
    addShort: 'ប្រមូល',
    addLabel: 'បន្ថែមទីកន្លែងនេះទៅការប្រមូលសាធារណៈ',
    noneYet: 'មិនទាន់មានការប្រមូល — បង្កើតមួយដំបូងខាងក្រោម។',
    createAndAdd: 'បង្កើត និងបន្ថែម',
    addedNotice: 'បានបន្ថែមទៅការប្រមូលរបស់អ្នក។',
    addFailed: 'មិនអាចបន្ថែមទីកន្លែងនោះបានទេ។',
    createFailed: 'មិនអាចបង្កើតការប្រមូលបានទេ។',
    sharedEyebrow: 'ការប្រមូលសាធារណៈ',
    notFound: 'ការប្រមូលនេះមិនមានទេ។',
    noPlaces: 'មិនទាន់មានទីកន្លែងក្នុងការប្រមូលនេះ។',
  },
  chat: {
    title: 'ការជជែកដំណើរ',
    localGuides: 'មគ្គុទ្ទេសក៍ក្នុងស្រុក',
    activeNow: 'កំពុងប្រើប្រាស់',
    typeMessage: 'សរសេរសារ...',
    sharePlace: 'ចែករំលែកទីកន្លែង',
    pinLocation: 'ខ្ទាស់ទីតាំង',
    shareItinerary: 'ផែនការដំណើរ',
    choosePlace: 'ខ្ទាស់ទីកន្លែងក្នុងការជជែក',
  },
  profile: {
    expertise: 'ជំនាញក្នុងស្រុក',
    services: 'បទពិសោធន៍ និងកន្លែងស្នាក់នៅ',
    servicesSubtitle: 'ធ្វើដំណើរយឺតៗ និងជួបអ្នកដែលស្គាល់ទេសភាពទាំងនេះច្បាស់បំផុត។',
    book: 'កក់បទពិសោធន៍',
  },
  payment: {
    secure: 'ការទូទាត់ KHQR ប្រកបដោយសុវត្ថិភាព',
    guestName: 'ឈ្មោះរបស់អ្នក',
    scanPay: 'ស្កេនដើម្បីទូទាត់ជាមួយធនាគារសមាជិកបាគង',
    confirm: 'បញ្ជាក់ការទូទាត់ភ្លាមៗ',
    received: 'បានទទួលការទូទាត់ភ្លាមៗ',
  },
  ranking: {
    title: 'បញ្ជីខេត្តកំពូលនៅកម្ពុជា',
    subtitle: 'ចង្វាក់រស់រវើកនៃទីកន្លែងដែលអ្នកដំណើរស្រឡាញ់ បង្កើតពីការចូលទស្សនា និងការវាយតម្លៃពិត។',
  },
  auth: {
    loginTitle: 'សូមស្វាគមន៍ត្រឡប់មកវិញ',
    loginSubtitle: 'ចូលគណនី ដើម្បីបង្ហោះកន្លែង រក្សាទុកកន្លែងពិសេស និងតាមដានអ្នកចែករំលែកក្នុងស្រុក។',
    registerTitle: 'ចូលរួមជាមួយសុខសាន្តដោយឥតគិតថ្លៃ',
    registerSubtitle: 'បង្កើតគណនីឥតគិតថ្លៃ ដើម្បីចែករំលែកកន្លែងលាក់ខ្លួនរបស់កម្ពុជា។',
    name: 'ឈ្មោះរបស់អ្នក',
    namePlaceholder: 'ឧ. ដារ៉ា សុខ',
    email: 'អ៊ីមែល',
    password: 'ពាក្យសម្ងាត់',
    confirm: 'បញ្ជាក់ពាក្យសម្ងាត់',
    loginAction: 'ចូលគណនី',
    registerAction: 'បង្កើតគណនី',
    noAccount: 'មិនទាន់មានគណនី?',
    haveAccount: 'មានគណនីរួចហើយ?',
    logout: 'ចាកចេញ',
    loginNav: 'ចូលគណនី',
    joinNav: 'ចុះឈ្មោះឥតគិតថ្លៃ',
    nameError: 'សូមបញ្ចូលឈ្មោះរបស់អ្នក (យ៉ាងតិច ២ តួអក្សរ)។',
    emailError: 'សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលដែលត្រឹមត្រូវ។',
    passwordError: 'ពាក្យសម្ងាត់ត្រូវមានយ៉ាងតិច ៨ តួអក្សរ។',
    confirmError: 'ពាក្យសម្ងាត់មិនដូចគ្នា។',
    genericError: 'មានកំហុសកើតឡើង។ សូមព្យាយាមម្ដងទៀត។',
    showPassword: 'បង្ហាញពាក្យសម្ងាត់',
    hidePassword: 'លាក់ពាក្យសម្ងាត់',
    composerLoginTitle: 'ចូលគណនី ដើម្បីចែករំលែកកន្លែងរបស់អ្នក',
    composerLoginBody: 'បង្ហោះ ចូលចិត្ត មតិ និងរក្សាទុក គឺឥតគិតថ្លៃ — អ្នកគ្រាន់តែត្រូវការគណនី។',
    composerLoginCta: 'ចូលគណនី ឬចុះឈ្មោះឥតគិតថ្លៃ',
    savedOnly: 'ចូលគណនី ដើម្បីរក្សាទុកកន្លែងក្នុងបញ្ជីរបស់អ្នក។',
  },
};

const translations: Record<Language, Dict> = { en, kh };

const aliases: Record<string, string> = {
  home: 'navigation.home',
  discover: 'navigation.discover',
  rankings: 'navigation.rankings',
  messages: 'navigation.messages',
  profile: 'navigation.profile',
  merchant: 'navigation.merchant',
  search: 'search.placeholder',
  feedTitle: 'feed.title',
  feedSubtitle: 'feed.subtitle',
  seeMore: 'common.seeMore',
  seeLess: 'common.seeLess',
  exploreBook: 'feed.exploreBook',
  discoveryTitle: 'discovery.title',
  discoverySubtitle: 'discovery.subtitle',
  allPlaces: 'common.allPlaces',
  nearby: 'discovery.nearby',
  budget: 'discovery.budget',
  travelChat: 'chat.title',
  all: 'common.all',
  localGuides: 'chat.localGuides',
  activeNow: 'chat.activeNow',
  typeMessage: 'chat.typeMessage',
  sharePlace: 'chat.sharePlace',
  pinLocation: 'chat.pinLocation',
  shareItinerary: 'chat.shareItinerary',
  choosePlace: 'chat.choosePlace',
  expertise: 'profile.expertise',
  services: 'profile.services',
  servicesSub: 'profile.servicesSubtitle',
  book: 'profile.book',
  securePayment: 'payment.secure',
  guestName: 'payment.guestName',
  scanPay: 'payment.scanPay',
  confirm: 'payment.confirm',
  received: 'payment.received',
  rankingTitle: 'ranking.title',
  rankingSub: 'ranking.subtitle',
  boost: 'feed.boost',
  featured: 'feed.featured',
  sponsored: 'common.sponsored',
  loading: 'common.loading',
  retry: 'common.retry',
};

function resolve(dict: Dict, path: string): string | undefined {
  const value = path.split('.').reduce<Dict | string | undefined>((node, key) => {
    if (!node || typeof node === 'string') return undefined;
    return node[key];
  }, dict);
  return typeof value === 'string' ? value : undefined;
}

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() =>
    localStorage.getItem('soksan-language') === 'kh' ? 'kh' : 'en',
  );

  useEffect(() => {
    localStorage.setItem('soksan-language', language);
    document.documentElement.lang = language === 'kh' ? 'km' : 'en';
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      toggleLanguage: () => setLanguage((prev) => (prev === 'en' ? 'kh' : 'en')),
      t: (key: string) => {
        const path = aliases[key] || key;
        return resolve(translations[language], path) || resolve(translations.en, path) || key;
      },
    }),
    [language],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
